version: "3.7"

services:
  subtitles:
    image: heitorcarneiro/subtitles-job-schedule:V0.0.1
    volumes:
      - /data/storage/tv:/tv
      - /data/storage/movies:/movies
      - /data/docker/subtitles/logs:/app/logs
    restart: unless-stopped
